"""remove api access token table

Revision ID: 25883baca06
Revises: 33f748cdc2f
Create Date: 2014-03-23 00:05:52.066581

"""

# revision identifiers, used by Alembic.
revision = '25883baca06'
down_revision = '33f748cdc2f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apiaccesstok')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apiaccesstok',
    sa.Column('id', sa.INTEGER(), server_default="nextval('apiaccesstok_id_seq'::regclass)", nullable=False),
    sa.Column('token', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('remote_addr', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('expire_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='apiaccesstok_pkey')
    )
    ### end Alembic commands ###
