"""add last notice and internal addresses

Revision ID: 2e6851ff437
Revises: 42a3f495ec4
Create Date: 2014-06-05 21:40:47.132595

"""

# revision identifiers, used by Alembic.
revision = '2e6851ff437'
down_revision = '42a3f495ec4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_expiry_notice', sa.DateTime(), nullable=True))
    op.add_column('vpnsessions', sa.Column('internal_ip4', sa.String(), nullable=True))
    op.add_column('vpnsessions', sa.Column('internal_ip6', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpnsessions', 'internal_ip6')
    op.drop_column('vpnsessions', 'internal_ip4')
    op.drop_column('users', 'last_expiry_notice')
    ### end Alembic commands ###
