"""add gateways table

Revision ID: 33f748cdc2f
Revises: 956b1aac1
Create Date: 2014-03-22 23:28:27.605724

"""

# revision identifiers, used by Alembic.
revision = '33f748cdc2f'
down_revision = '956b1aac1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('isp_name', sa.String(length=32), nullable=False),
    sa.Column('isp_url', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('ipv4', sa.String(), nullable=True),
    sa.Column('ipv6', sa.String(), nullable=True),
    sa.Column('bps', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gateways')
    ### end Alembic commands ###
