"""add pwresettoken

Revision ID: 44db46b919f
Revises: 1deecd313c4
Create Date: 2014-01-12 00:26:21.920085

"""

# revision identifiers, used by Alembic.
revision = '44db46b919f'
down_revision = '1deecd313c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pwresettoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pwresettoken')
    ### end Alembic commands ###
