"""add giftcodes.free_only

Revision ID: 956b1aac1
Revises: a8195fe5a5
Create Date: 2014-01-28 20:02:54.815149

"""

# revision identifiers, used by Alembic.
revision = '956b1aac1'
down_revision = 'a8195fe5a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giftcodes', sa.Column('free_only', sa.Boolean(), server_default='true', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giftcodes', 'free_only')
    ### end Alembic commands ###
