"""add referrer

Revision ID: a8195fe5a5
Revises: 44db46b919f
Create Date: 2014-01-23 21:40:21.766716

"""

# revision identifiers, used by Alembic.
revision = 'a8195fe5a5'
down_revision = '44db46b919f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referrer_id')
    ### end Alembic commands ###
